import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import SidebarLayout from "./(home)/components/SidebarLayout";
import "./globals.css";
import { House, LogOut, NotebookPen, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SidebarLayout top="PESQUISA AQUI"
          second={
            <div className="flex flex-col gap-4">
              <Link className="flex gap-2" href="/" > <House></House>Home</Link>
              <Link className="flex gap-2" href="pesquisa/" ><NotebookPen></NotebookPen>Pesquisa</Link>
              <Link className="flex gap-2" href="pesquisadores/" ><UsersRound></UsersRound>Pesquisadores</Link>
            </div>
          }
          bottom={<Button variant="ghost"><LogOut></LogOut> Sair</Button>
          }>
          {children}</SidebarLayout>
      </body>
    </html>
  );
}
